# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 792122605c83ea42510ba7cbb751796d3c3a364c762ec4eff57f0a93d16dd56f87f8304095212f4709aa286baa3951be968dc4d63b8ae69123588db31bd1433e

test:
  secret_key_base: 3e799de90e59330deee0dc896fb999ad3b2d57939fead4c218c26429a37ec209df6830667610e897784e6249fb3d1d4f396f0bbfb20fe6ac0e5884c67d299dc2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
